(feat): Added escape_to_host
5GSEC/nimbus pull request #79
Opened 2024-03-15 04:52 UTC by VedRatan

## Description

 This PR introduces a new capability in Kubearmor for Escape-To-Host use case.

Fixes # (issue)
Closes #74 

**Does this PR introduce a breaking change?**

## Checklist

- [x] PR title follows the `<type>: <description>` convention
- [ ] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
- [ ] I have updated the [documentation](../docs) accordingly
- [ ] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
- [ ] I have performed a self-review of my code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Additional information for reviewer

#### Mention if this PR is part of any design or a continuation of previous PRs

2024-03-20 05:54 UTC, anurag-rajawat commented on pkg/adapter/nimbus-kubearmor/processor/kspbuilder.go
> +func disallowMatchPath() kubearmorv1.KubeArmorPolicy {
Isn't it possible to leverage [swDeploymentTools](https://github.com/5GSEC/nimbus/blob/b91563b0ccd36deee1c6afd73cf51fd2aa25aae8/pkg/adapter/nimbus-kubearmor/processor/kspbuilder.go#L83) policy by adding `wget` and `curl` executables path there?

E.g.,
```go
...
case idpool.DisallowChRoot:
    policy :=  swDeploymentToolsKsp()
    policy.Spec.Process.MatchPaths = append(ksp.Spec.Process.MatchPaths, wget-path, curl-path)
    return policy
...
```

2024-03-20 11:15 UTC, anurag-rajawat submitted a review, later dismissed

2024-03-21 11:52 UTC, anurag-rajawat commented
Please resolve conflicts and rebase.

2024-03-22 16:31 UTC, anurag-rajawat reviewed
A comment to address and we're good to merge.

2024-03-22 16:31 UTC, anurag-rajawat commented on pkg/adapter/nimbus-kubearmor/Dockerfile
> +ADD internal/ internal/
Do we need `internal` directory? Since it contains nimbus controllers only.

2024-03-22 16:37 UTC, anurag-rajawat approved these changes

2024-03-22 17:45 UTC, anurag-rajawat requested changes

2024-03-22 17:45 UTC, anurag-rajawat commented on pkg/adapter/nimbus-kubearmor/Makefile
Update `docker-buildx` target to point to correct context.
https://github.com/5GSEC/nimbus/blob/4c38a71dcc73a337877ff8dc6ede4bd470ce6ae8/pkg/adapter/nimbus-kubearmor/Makefile#L34

2024-03-24 05:06 UTC, VedRatan commented
@anurag-rajawat we can now merge this I guess.

2024-03-24 05:06 UTC, VedRatan commented on pkg/adapter/nimbus-kubearmor/Makefile
done with this.

2024-03-26 05:43 UTC, anurag-rajawat reviewed
Please squash your commits.

2024-03-26 08:05 UTC, anurag-rajawat approved these changes

2024-03-26 08:18 UTC, merged