(enhancement): Added relative dependencies for Netpol-Adapter
5GSEC/nimbus pull request #87
Opened 2024-03-20 14:07 UTC by VedRatan

## Description

 This PR introduces the relative dependencies that will make the netpol-adapter module to use the relative dependency of the parent directory instead of absolute github dependency.

Fixes # (issue)

**Does this PR introduce a breaking change?**

## Checklist

- [x] PR title follows the `<type>: <description>` convention
- [ ] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
- [ ] I have updated the [documentation](../docs) accordingly
- [ ] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
- [ ] I have performed a self-review of my code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Additional information for reviewer

#### Mention if this PR is part of any design or a continuation of previous PRs

2024-03-20 14:35 UTC, anurag-rajawat commented on pkg/adapter/nimbus-netpol/Dockerfile
> +ADD internal/ internal/
Do we need `internal` directory? Since it contains nimbus controllers.

2024-03-21 11:50 UTC, anurag-rajawat commented
Please resolve conflicts, rebase and squash commits, and then we're good to merge this.

2024-03-21 12:15 UTC, VedRatan commented
@anurag-rajawat ig we're good to merge this one

2024-03-21 12:20 UTC, anurag-rajawat requested changes
Please squash your git commits and address one minor comment.

2024-03-21 12:20 UTC, anurag-rajawat commented on pkg/adapter/nimbus-netpol/go.mod
> +replace github.com/5GSEC/nimbus => ../../../../nimbus
Please move this directive below the `go 1.22` line.

2024-03-22 16:32 UTC, anurag-rajawat approved these changes

2024-03-22 16:37 UTC, VedRatan commented
can we merge this? @anurag-rajawat

2024-03-22 16:38 UTC, merged